//
//  SigningCertificate.swift
//  Luna
//
//  The record of a signing identity the user brought with them.
//
//  WHAT IS STORED HERE, AND WHAT IS NOT
//  ------------------------------------
//  This type holds only what is needed to *display* a certificate and to find
//  the material it came from: subject fields, validity dates, a fingerprint,
//  the name of the `.p12` on disk. The private key lives in the keychain; the
//  `.p12` export password lives in the keychain; the `.p12` itself stays on
//  disk, encrypted by that same password.
//
//  There is deliberately no field here for a key, a password, or any DER
//  blob. `SecKey` is not `Codable`, which means the one mistake worth
//  guarding against — dropping a private key into a JSON file that gets
//  synced, backed up, and mailed around — does not compile.
//

import Foundation

/// A signing identity imported by the user.
///
/// The `id` is generated by Luna at import time and is the *only* thing that
/// ties the three pieces together: this record, the `.p12` in
/// `Certificates/<id>/`, and the keychain items under `…<id>`.
struct SigningCertificate: Identifiable, Codable, Hashable {

    let id: UUID

    /// What the user sees in a picker. Defaults to the common name, but is
    /// editable so a user juggling three certificates that all read
    /// "iPhone Distribution: Some Name" can tell them apart.
    var displayName: String

    /// `subject.CN` — typically `iPhone Distribution: Team Name`.
    var commonName: String

    /// `subject.OU` — the ten-character team identifier.
    ///
    /// Apple puts the team ID in the organizational *unit* field, not the
    /// organization field; the organization carries the human-readable team
    /// name instead. Getting these two the wrong way round produces a
    /// certificate that looks right and fails to match any profile.
    var teamID: String

    /// `subject.O` — the team name as shown on the developer portal.
    var organization: String

    /// Decimal serial number, for display alongside the team ID.
    var serialNumber: String

    var notBefore: Date
    var notAfter: Date

    /// SHA-256 of the certificate's DER bytes.
    ///
    /// This is the value provisioning profiles list under
    /// `DeveloperCertificates`, and the value used to match a `.p12` against
    /// a `.mobileprovision`. Stored as lowercase hex so it can be compared
    /// with the profile's `Data` directly.
    var sha256: String

    /// Human-readable key type, e.g. `RSA-2048` or `EC-P256`.
    ///
    /// Kept as a description rather than a key handle: the signing code
    /// re-derives the algorithm from the actual `SecKey` each time, since the
    /// keychain is the source of truth and this record could be edited by
    /// hand.
    var keyAlgorithm: String

    /// File name of the imported `.p12` inside the certificate's folder.
    var p12FileName: String

    var importedAt: Date

    /// The provisioning profile this certificate was imported with, if any.
    ///
    /// Optional because a `.p12` is useful on its own for inspection, and
    /// because a user may reasonably import the profile in a second pass.
    /// A certificate without a profile can be listed and deleted but cannot
    /// be used to sign — see `isUsable`.
    var profile: ProvisioningProfileSummary?

    // MARK: - Derived

    /// True when the certificate is within its validity window right now.
    var isValid: Bool {
        let now = Date()
        return now >= notBefore && now <= notAfter
    }

    /// True when Luna has everything needed to actually sign with this
    /// identity: a valid certificate *and* a non-expired profile.
    var isUsable: Bool {
        guard isValid, let profile else { return false }
        return profile.expirationDate > Date()
    }

    /// Why the certificate cannot be used, or `nil` if it can.
    ///
    /// The UI shows this verbatim, so it reads as a sentence rather than as a
    /// diagnostic code.
    var unusableReason: String? {
        if !isValid {
            return notAfter < Date()
                ? "证书已于 \(Self.dateFormatter.string(from: notAfter)) 过期"
                : "证书尚未生效（生效时间 \(Self.dateFormatter.string(from: notBefore))）"
        }
        guard let profile else { return "缺少描述文件（.mobileprovision）" }
        if profile.expirationDate <= Date() {
            return "描述文件已于 \(Self.dateFormatter.string(from: profile.expirationDate)) 过期"
        }
        return nil
    }

    /// A one-line summary for list rows: team ID and expiry.
    var subtitle: String {
        "\(teamID) · \(keyAlgorithm) · 有效至 \(Self.dateFormatter.string(from: notAfter))"
    }

    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter
    }()
}

/// The parts of a `.mobileprovision` Luna cares about.
///
/// A provisioning profile is a plist wrapped in a PKCS#7 signature. Once the
/// wrapper is stripped the plist holds a dozen keys; only these have any
/// bearing on whether a signature will be accepted, so only these are kept.
struct ProvisioningProfileSummary: Codable, Hashable {

    /// `Name` — the profile's display name on the developer portal.
    var name: String

    /// `UUID` — the profile's identifier. iOS looks up an embedded profile by
    /// this value, so it must survive to `embedded.mobileprovision`.
    var profileUUID: String

    /// `TeamIdentifier[0]`.
    var teamID: String

    /// `Entitlements.application-identifier` — e.g. `ABCDE12345.com.foo.bar`,
    /// or `ABCDE12345.*` for a wildcard profile.
    var applicationIdentifier: String

    var expirationDate: Date

    /// `ProvisionedDevices` count. Zero for enterprise and App Store
    /// profiles, which are not device-limited.
    var provisionedDeviceCount: Int

    /// True when `applicationIdentifier` ends in `*`.
    ///
    /// Wildcard profiles are the common case for sideloading: they match any
    /// bundle ID under the team, which is why signing has to substitute the
    /// guest's real bundle ID for the `*` before writing entitlements.
    var isWildcard: Bool {
        applicationIdentifier.hasSuffix("*")
    }

    /// `DeveloperCertificates` — SHA-256 fingerprints of the certificates
    /// this profile is willing to accept, lowercase hex.
    var developerCertificateShas: [String]

    /// The team identifier parsed out of `applicationIdentifier`.
    ///
    /// Used to cross-check against the certificate's `OU`: a profile and a
    /// certificate from different teams will never validate together, and
    /// catching that at import time is far better than catching it on device
    /// with an opaque `0xe8008015`.
    var applicationIdentifierTeamPrefix: String {
        applicationIdentifier.split(separator: ".").first.map(String.init) ?? ""
    }
}
